[package]
name = "abc145"
version = "0.1.0"
authors = ["Yolie <yolie@ezff.dev>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = { version = "0.3.6", features = ["derive"] }

[profile.release]
lto = true
panic = 'abort'
