[package]
name = "abc132"
version = "0.1.0"
authors = ["Yolie <yolie@ezff.dev>"]
edition = "2018"

# dependencies added to new project
[dependencies]
whiteread = "0.5.0"

[profile.release]
lto = true
panic = 'abort'
